# Generated by Django 4.2.4 on 2023-08-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_shelf_bookshelf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookshelf",
            options={
                "ordering": ("shelved_on",),
                "verbose_name_plural": "Book Shelves",
            },
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="shelf",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Shelf",
        ),
    ]
