# Generated by Django 4.2.4 on 2023-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_bookshelf_options_alter_bookshelf_shelf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
